export const city = [
  {
    id: '%E5%9F%BA%E9%9A%86%E5%B8%82',
    es_name: 'Keelung',
    bgc: 'Keelung',
    locationName: '基隆市',
  },
  {
    id: '%E8%87%BA%E5%8C%97%E5%B8%82',
    es_name: 'Taipei',
    bgc: 'Taipei',
    locationName: '臺北市',
  },
  {
    id: '%E6%96%B0%E5%8C%97%E5%B8%82',
    es_name: 'NewTaipei',
    bgc: 'NewTaipei',
    locationName: '新北市',
  },
  {
    id: '%E6%A1%83%E5%9C%92%E5%B8%82',
    es_name: 'Taoyuan',
    bgc: 'Taoyuan',
    locationName: '桃園市',
  },
  {
    id: '%E6%96%B0%E7%AB%B9%E5%B8%82',
    es_name: 'Hsinchu',
    bgc: 'Hsinchu',
    locationName: '新竹市',
  },
  {
    id: '%E6%96%B0%E7%AB%B9%E7%B8%A3',
    es_name: 'Hsinchu',
    bgc: 'Hsinchu-2',
    locationName: '新竹縣',
  },
  {
    id: '%E8%8B%97%E6%A0%97%E7%B8%A3',
    es_name: 'Miaoli',
    bgc: 'Miaoli',
    locationName: '苗栗縣',
  },
  {
    id: '%E8%87%BA%E4%B8%AD%E5%B8%82',
    es_name: 'Taichung',
    bgc: 'Taichung',
    locationName: '臺中市',
  },
  {
    id: '%E5%BD%B0%E5%8C%96%E7%B8%A3',
    es_name: 'Changhua',
    bgc: 'Changhua',
    locationName: '彰化縣',
  },
  {
    id: '%E5%8D%97%E6%8A%95%E7%B8%A3',
    es_name: 'Nantou',
    bgc: 'Nantou',
    locationName: '南投縣',
  },
  {
    id: '%E9%9B%B2%E6%9E%97%E7%B8%A3',
    es_name: 'Yunlin',
    bgc: 'Yunlin',
    locationName: '雲林縣',
  },
  {
    id: '%E5%98%89%E7%BE%A9%E5%B8%82',
    es_name: 'Chiayi',
    bgc: 'Chiayi-2',
    locationName: '嘉義市',
  },
  {
    id: '%E5%98%89%E7%BE%A9%E7%B8%A3',
    es_name: 'Chiayi',
    bgc: 'Chiayi',
    locationName: '嘉義縣',
  },
  {
    id: '%E8%87%BA%E5%8D%97%E5%B8%82',
    es_name: 'Tainan',
    bgc: 'Tainan',
    locationName: '臺南市',
  },
  {
    id: '%E9%AB%98%E9%9B%84%E5%B8%82',
    es_name: 'Kaohsiung',
    bgc: 'Kaohsiung',
    locationName: '高雄市',
  },
  {
    id: '%E5%B1%8F%E6%9D%B1%E7%B8%A3',
    es_name: 'Pingtung',
    bgc: 'Pingtung',
    locationName: '屏東縣',
  },
  {
    id: '%E5%AE%9C%E8%98%AD%E7%B8%A3',
    es_name: 'Yilan',
    bgc: 'Yilan',
    locationName: '宜蘭縣',
  },
  {
    id: '%E8%8A%B1%E8%93%AE%E7%B8%A3',
    es_name: 'Hualien',
    bgc: 'Hualien',
    locationName: '花蓮縣',
  },
  {
    id: '%E8%87%BA%E6%9D%B1%E7%B8%A3',
    es_name: 'Taitung',
    bgc: 'Taitung',
    locationName: '臺東縣',
  },
  {
    id: '%E6%BE%8E%E6%B9%96%E7%B8%A3',
    es_name: 'Penghu',
    bgc: 'Penghu',
    locationName: '澎湖縣',
  },
  {
    id: '%E9%87%91%E9%96%80%E7%B8%A3',
    es_name: 'Kinmen',
    bgc: 'Kinmen',
    locationName: '金門縣',
  },
  {
    id: '%E9%80%A3%E6%B1%9F%E7%B8%A3',
    es_name: 'Lienchiang',
    bgc: 'Lienchiang',
    locationName: '連江縣',
  },
];
